### ISSUE TITLE
driver = webdriver.PhantomJS()  causes selenium.common.exceptions.WebDriverException: Message: Service phantomjs unexpectedly exited. Status code was: 1

### ISSUE THREAD

**Issue by AlphaCentauriEpsilonPi** [detro/ghostdriver#552]
Environment: shared hosting account
OS:  FreeBSD 10.3-STABLE amd64

phantomjs 2.1.1
selenium Version: 0.2.11
Python 2.7.13

prog.py
```
from selenium import webdriver

#here it fails
driver = webdriver.PhantomJS() 

#this also fails, path is correct
#driver = webdriver.PhantomJS('/usr/local/bin/phantomjs')

#driver.set_window_size(1120, 550)
#driver.get("https://duckduckgo.com/")
#driver.find_element_by_id('search_form_input_homepage').send_keys("realpython")
#driver.find_element_by_id("search_button_homepage").click()
#print driver.current_url
#driver.quit()
```

```
$ virtualenv newvenv
$ source newvenv/bin/activate
$ pip install selenium
$ npm install ghostdriver
$ python prog.py
Traceback (most recent call last):
  File "prog.py", line 2, in <module>
    driver = webdriver.PhantomJS()
  File "/usr/home/USER/pyth/pythselenium/lib/python2.7/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/usr/home/USER/pyth/pythselenium/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 96, in start
    self.assert_process_still_running()
  File "/usr/home/USER/pyth/pythselenium/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service phantomjs unexpectedly exited. Status code was: 1
```

**Comment by jesg** [comment]
this issue is fixed in ghostdriver 2.0. ghostdriver 2.0 is packaged in an npm package.

**Comment by AlphaCentauriEpsilonPiBis** [comment]
@jesg 
>this issue is fixed in ghostdriver 2.0. ghostdriver 2.0 is packaged in an npm package.

How to use that version?
As I mentioned before in log I do 

```
npm install ghostdriver
```

I assume it's enought to download mentioned version?

I also tried to do

```
npm cache clean
npm cache clean ghostdriver
npm install ghostdriber@2.0
```

Also  set 
~/node_modules/ghostdriver/bin
to the PATH before /bin/ paths from root partition, to avoid using any global version. 

Yet it is not enough or it is not related to the bug that was fixed.

Still the same error.

**Comment by jesg** [comment]
@AlphaCentauriEpsilonPi 

you need to pass in a different executable to the selenium client.

```
driver = webdriver.PhantomJS('<user's home dir>/node_modules/.bin/ghostdriver') 
```
